<a href="https://colab.research.google.com/github/Harjot-Kaur25/EDA-/blob/main/DATA_PREP_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Analyzing Student Participation

In [14]:
import pandas as pd
import numpy as np

# --- Course Data Preparation ---
df1SE = pd.DataFrame({
    'StudentID': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
    'ScoreSE' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]
})
df2SE = pd.DataFrame({
    'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
    'ScoreSE': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]
})

df1ML = pd.DataFrame({
    'StudentID': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
    'ScoreML' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]
})
df2ML = pd.DataFrame({
    'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    'ScoreML': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]
})

# Combine SE and ML data
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

# Answer Department Questions
total_students = pd.concat([dfSE['StudentID'], dfML['StudentID']]).nunique()
se_only = dfSE[~dfSE['StudentID'].isin(dfML['StudentID'])]
ml_only = dfML[~dfML['StudentID'].isin(dfSE['StudentID'])]

print(f"Total unique students: {total_students}")
print(f"Students only in SE: {len(se_only)}")
print(f"Students only in ML: {len(ml_only)}")

Total unique students: 30
Students only in SE: 5
Students only in ML: 4

In [15]:
import pandas as pd
import numpy as np

# --- Reshaping with Hierarchical Indexing ---
data = np.arange(15).reshape((3, 5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])

print("Original DataFrame:")
display(dframe1)

# Stacking the DataFrame
stacked = dframe1.stack()
print("\nStacked Series (Hierarchical Index):")
display(stacked)

# Unstacking back to DataFrame
print("\nUnstacked back to DataFrame:")
display(stacked.unstack())

# --- Concatenating Series with Keys ---
series1 = pd.Series([0, 111, 222, 333], index=['zeros', 'ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
print("\nConcatenated Series with keys:")
display(frame2)

print("\nUnstacked Concatenation:")
display(frame2.unstack())

Original DataFrame:

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

Stacked Series (Hierarchical Index):

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

Unstacked back to DataFrame:

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

Concatenated Series with keys:

Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixs      666
dtype: int64

Unstacked Concatenation:

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN